In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4689, 4293, 429, 9064],
 [4689, 4293, 429, 703],
 [4689, 8084, 429, 2415],
 [4156, 7002, 2881, 7034, 5475],
 [4156, 7002, 2881, 7034, 6758],
 [3870, 4689, 7528, 429, 4130],
 [609, 2602, 4269, 7034]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4689 4293  429 9064]
 [   0    0    0    0 4689 4293  429  703]
 [   0    0    0    0 4689 8084  429 2415]
 [   0    0    0 4156 7002 2881 7034 5475]
 [   0    0    0 4156 7002 2881 7034 6758]
 [   0    0    0 3870 4689 7528  429 4130]
 [   0    0    0    0  609 2602 4269 7034]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 72ms/step


array([[[ 0.01800792, -0.01428759,  0.01201613, -0.04901091,
          0.02348782, -0.00622041, -0.00901722, -0.00615992,
         -0.01167203, -0.04817634],
        [ 0.01800792, -0.01428759,  0.01201613, -0.04901091,
          0.02348782, -0.00622041, -0.00901722, -0.00615992,
         -0.01167203, -0.04817634],
        [ 0.01800792, -0.01428759,  0.01201613, -0.04901091,
          0.02348782, -0.00622041, -0.00901722, -0.00615992,
         -0.01167203, -0.04817634],
        [ 0.01800792, -0.01428759,  0.01201613, -0.04901091,
          0.02348782, -0.00622041, -0.00901722, -0.00615992,
         -0.01167203, -0.04817634],
        [-0.02438754,  0.01940154,  0.01348264, -0.02280722,
         -0.01692901,  0.02465922,  0.00917054,  0.0410239 ,
          0.03439162,  0.04393431],
        [ 0.04056711, -0.00954425, -0.03461757, -0.01840595,
         -0.03690814,  0.03520895, -0.04361596,  0.01508507,
         -0.01734096,  0.04024184],
        [ 0.00182414, -0.02570136,  0.00026058, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4689, 4293,  429, 9064])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 29ms/step


array([[ 0.01800792, -0.01428759,  0.01201613, -0.04901091,  0.02348782,
        -0.00622041, -0.00901722, -0.00615992, -0.01167203, -0.04817634],
       [ 0.01800792, -0.01428759,  0.01201613, -0.04901091,  0.02348782,
        -0.00622041, -0.00901722, -0.00615992, -0.01167203, -0.04817634],
       [ 0.01800792, -0.01428759,  0.01201613, -0.04901091,  0.02348782,
        -0.00622041, -0.00901722, -0.00615992, -0.01167203, -0.04817634],
       [ 0.01800792, -0.01428759,  0.01201613, -0.04901091,  0.02348782,
        -0.00622041, -0.00901722, -0.00615992, -0.01167203, -0.04817634],
       [-0.02438754,  0.01940154,  0.01348264, -0.02280722, -0.01692901,
         0.02465922,  0.00917054,  0.0410239 ,  0.03439162,  0.04393431],
       [ 0.04056711, -0.00954425, -0.03461757, -0.01840595, -0.03690814,
         0.03520895, -0.04361596,  0.01508507, -0.01734096,  0.04024184],
       [ 0.00182414, -0.02570136,  0.00026058, -0.02685587,  0.03004545,
        -0.0218161 ,  0.02364394, -0.04970039